/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `activitat`;

CREATE TABLE `activitat` (
  `nom` VARCHAR(128) NOT NULL PRIMARY KEY,
  `durada` INT NOT NULL)
 ENGINE=InnoDB;

ALTER TABLE `activitat`
  ADD CONSTRAINT `activitat_nom_fk`
    FOREIGN KEY (`nom`)
    REFERENCES `experiencia` (`nom`)
    ON DELETE CASCADE;

