/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `escapada`;

CREATE TABLE `escapada` (
  `nom` VARCHAR(128) NOT NULL PRIMARY KEY,
  `hotel` TEXT NOT NULL,
  `num_nits` INT NOT NULL)
 ENGINE=InnoDB;

ALTER TABLE `escapada`
  ADD CONSTRAINT `escapada_nom_fk`
    FOREIGN KEY (`nom`)
    REFERENCES `experiencia` (`nom`)
    ON DELETE CASCADE;

