// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "experiencia-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy
#include <typeinfo>

#include <odb/polymorphic-map.hxx>

#include <odb/mysql/traits.hxx>
#include <odb/mysql/database.hxx>
#include <odb/mysql/transaction.hxx>
#include <odb/mysql/connection.hxx>
#include <odb/mysql/statement.hxx>
#include <odb/mysql/statement-cache.hxx>
#include <odb/mysql/polymorphic-object-statements.hxx>
#include <odb/mysql/container-statements.hxx>
#include <odb/mysql/exceptions.hxx>
#include <odb/mysql/polymorphic-object-result.hxx>
#include <odb/mysql/enum.hxx>

namespace odb
{
  // experiencia
  //

  struct access::object_traits_impl< ::experiencia, id_mysql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      mysql::connection&,
      image_type&,
      id_image_type&,
      mysql::binding&,
      mysql::binding&)
    {
    }
  };

  access::object_traits_impl< ::experiencia, id_mysql >::id_type
  access::object_traits_impl< ::experiencia, id_mysql >::
  id (const image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        id,
        i._nom_value,
        i._nom_size,
        i._nom_null);
    }

    return id;
  }

  access::object_traits_impl< ::experiencia, id_mysql >::discriminator_type
  access::object_traits_impl< ::experiencia, id_mysql >::
  discriminator (const image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    discriminator_type d;
    {
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        d,
        i.typeid_value,
        i.typeid_size,
        i.typeid_null);
    }

    return d;
  }

  bool access::object_traits_impl< ::experiencia, id_mysql >::
  grow (image_type& i,
        my_bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // _nom
    //
    if (t[0UL])
    {
      i._nom_value.capacity (i._nom_size);
      grew = true;
    }

    // typeid_
    //
    if (t[1UL])
    {
      i.typeid_value.capacity (i.typeid_size);
      grew = true;
    }

    // _descripcio
    //
    if (t[2UL])
    {
      i._descripcio_value.capacity (i._descripcio_size);
      grew = true;
    }

    // _ciutat
    //
    if (t[3UL])
    {
      i._ciutat_value.capacity (i._ciutat_size);
      grew = true;
    }

    // _maxim_places
    //
    t[4UL] = 0;

    // _preu
    //
    t[5UL] = 0;

    // _data_alta
    //
    if (t[6UL])
    {
      i._data_alta_value.capacity (i._data_alta_size);
      grew = true;
    }

    // _num_reserves
    //
    t[7UL] = 0;

    return grew;
  }

  void access::object_traits_impl< ::experiencia, id_mysql >::
  bind (MYSQL_BIND* b,
        image_type& i,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    std::size_t n (0);

    // _nom
    //
    if (sk != statement_update)
    {
      b[n].buffer_type = MYSQL_TYPE_STRING;
      b[n].buffer = i._nom_value.data ();
      b[n].buffer_length = static_cast<unsigned long> (
        i._nom_value.capacity ());
      b[n].length = &i._nom_size;
      b[n].is_null = &i._nom_null;
      n++;
    }

    // typeid_
    //
    if (sk != statement_update)
    {
      b[n].buffer_type = MYSQL_TYPE_STRING;
      b[n].buffer = i.typeid_value.data ();
      b[n].buffer_length = static_cast<unsigned long> (
        i.typeid_value.capacity ());
      b[n].length = &i.typeid_size;
      b[n].is_null = &i.typeid_null;
      n++;
    }

    // _descripcio
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i._descripcio_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i._descripcio_value.capacity ());
    b[n].length = &i._descripcio_size;
    b[n].is_null = &i._descripcio_null;
    n++;

    // _ciutat
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i._ciutat_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i._ciutat_value.capacity ());
    b[n].length = &i._ciutat_size;
    b[n].is_null = &i._ciutat_null;
    n++;

    // _maxim_places
    //
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i._maxim_places_value;
    b[n].is_null = &i._maxim_places_null;
    n++;

    // _preu
    //
    b[n].buffer_type = MYSQL_TYPE_FLOAT;
    b[n].buffer = &i._preu_value;
    b[n].is_null = &i._preu_null;
    n++;

    // _data_alta
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i._data_alta_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i._data_alta_value.capacity ());
    b[n].length = &i._data_alta_size;
    b[n].is_null = &i._data_alta_null;
    n++;

    // _num_reserves
    //
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i._num_reserves_value;
    b[n].is_null = &i._num_reserves_null;
    n++;
  }

  void access::object_traits_impl< ::experiencia, id_mysql >::
  bind (MYSQL_BIND* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.id_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.id_value.capacity ());
    b[n].length = &i.id_size;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::experiencia, id_mysql >::
  init (image_type& i,
        const object_type& o,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    bool grew (false);

    // _nom
    //
    if (sk == statement_insert)
    {
      ::std::string const& v =
        o._nom;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i._nom_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i._nom_value,
        size,
        is_null,
        v);
      i._nom_null = is_null;
      i._nom_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i._nom_value.capacity ());
    }

    // typeid_
    //
    if (sk == statement_insert)
    {
      const info_type& di (map->find (typeid (o)));

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.typeid_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.typeid_value,
        size,
        is_null,
        di.discriminator);
      i.typeid_null = is_null;
      i.typeid_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.typeid_value.capacity ());
    }

    // _descripcio
    //
    {
      ::std::string const& v =
        o._descripcio;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i._descripcio_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i._descripcio_value,
        size,
        is_null,
        v);
      i._descripcio_null = is_null;
      i._descripcio_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i._descripcio_value.capacity ());
    }

    // _ciutat
    //
    {
      ::std::string const& v =
        o._ciutat;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i._ciutat_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i._ciutat_value,
        size,
        is_null,
        v);
      i._ciutat_null = is_null;
      i._ciutat_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i._ciutat_value.capacity ());
    }

    // _maxim_places
    //
    {
      int const& v =
        o._maxim_places;

      bool is_null (false);
      mysql::value_traits<
          int,
          mysql::id_long >::set_image (
        i._maxim_places_value, is_null, v);
      i._maxim_places_null = is_null;
    }

    // _preu
    //
    {
      float const& v =
        o._preu;

      bool is_null (false);
      mysql::value_traits<
          float,
          mysql::id_float >::set_image (
        i._preu_value, is_null, v);
      i._preu_null = is_null;
    }

    // _data_alta
    //
    {
      ::std::string const& v =
        o._data_alta;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i._data_alta_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i._data_alta_value,
        size,
        is_null,
        v);
      i._data_alta_null = is_null;
      i._data_alta_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i._data_alta_value.capacity ());
    }

    // _num_reserves
    //
    {
      int const& v =
        o._num_reserves;

      bool is_null (false);
      mysql::value_traits<
          int,
          mysql::id_long >::set_image (
        i._num_reserves_value, is_null, v);
      i._num_reserves_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::experiencia, id_mysql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // _nom
    //
    {
      ::std::string& v =
        o._nom;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i._nom_value,
        i._nom_size,
        i._nom_null);
    }

    // _descripcio
    //
    {
      ::std::string& v =
        o._descripcio;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i._descripcio_value,
        i._descripcio_size,
        i._descripcio_null);
    }

    // _ciutat
    //
    {
      ::std::string& v =
        o._ciutat;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i._ciutat_value,
        i._ciutat_size,
        i._ciutat_null);
    }

    // _maxim_places
    //
    {
      int& v =
        o._maxim_places;

      mysql::value_traits<
          int,
          mysql::id_long >::set_value (
        v,
        i._maxim_places_value,
        i._maxim_places_null);
    }

    // _preu
    //
    {
      float& v =
        o._preu;

      mysql::value_traits<
          float,
          mysql::id_float >::set_value (
        v,
        i._preu_value,
        i._preu_null);
    }

    // _data_alta
    //
    {
      ::std::string& v =
        o._data_alta;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i._data_alta_value,
        i._data_alta_size,
        i._data_alta_null);
    }

    // _num_reserves
    //
    {
      int& v =
        o._num_reserves;

      mysql::value_traits<
          int,
          mysql::id_long >::set_value (
        v,
        i._num_reserves_value,
        i._num_reserves_null);
    }
  }

  void access::object_traits_impl< ::experiencia, id_mysql >::
  init (id_image_type& i, const id_type& id)
  {
    bool grew (false);
    {
      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.id_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.id_value,
        size,
        is_null,
        id);
      i.id_null = is_null;
      i.id_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.id_value.capacity ());
    }

    if (grew)
      i.version++;
  }

  access::object_traits_impl< ::experiencia, id_mysql >::map_type*
  access::object_traits_impl< ::experiencia, id_mysql >::map;

  const access::object_traits_impl< ::experiencia, id_mysql >::abstract_info_type
  access::object_traits_impl< ::experiencia, id_mysql >::info (
    typeid (::experiencia),
    0,
    0);

  const char access::object_traits_impl< ::experiencia, id_mysql >::persist_statement[] =
  "INSERT INTO `experiencia` "
  "(`nom`, "
  "`typeid`, "
  "`descripcio`, "
  "`ciutat`, "
  "`maxim_places`, "
  "`preu`, "
  "`data_alta`, "
  "`num_reserves`) "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::experiencia, id_mysql >::find_statement[] =
  "SELECT "
  "`experiencia`.`nom`, "
  "`experiencia`.`typeid`, "
  "`experiencia`.`descripcio`, "
  "`experiencia`.`ciutat`, "
  "`experiencia`.`maxim_places`, "
  "`experiencia`.`preu`, "
  "`experiencia`.`data_alta`, "
  "`experiencia`.`num_reserves` "
  "FROM `experiencia` "
  "WHERE `experiencia`.`nom`=?";

  const char access::object_traits_impl< ::experiencia, id_mysql >::
  find_discriminator_statement[] =
  "SELECT "
  "`experiencia`.`typeid` "
  "FROM `experiencia` "
  "WHERE `experiencia`.`nom`=?";

  const char access::object_traits_impl< ::experiencia, id_mysql >::update_statement[] =
  "UPDATE `experiencia` "
  "SET "
  "`descripcio`=?, "
  "`ciutat`=?, "
  "`maxim_places`=?, "
  "`preu`=?, "
  "`data_alta`=?, "
  "`num_reserves`=? "
  "WHERE `nom`=?";

  const char access::object_traits_impl< ::experiencia, id_mysql >::erase_statement[] =
  "DELETE FROM `experiencia` "
  "WHERE `nom`=?";

  const char access::object_traits_impl< ::experiencia, id_mysql >::query_statement[] =
  "SELECT "
  "`experiencia`.`nom`, "
  "`experiencia`.`typeid`, "
  "`experiencia`.`descripcio`, "
  "`experiencia`.`ciutat`, "
  "`experiencia`.`maxim_places`, "
  "`experiencia`.`preu`, "
  "`experiencia`.`data_alta`, "
  "`experiencia`.`num_reserves` "
  "FROM `experiencia`";

  const char access::object_traits_impl< ::experiencia, id_mysql >::erase_query_statement[] =
  "DELETE FROM `experiencia`";

  const char access::object_traits_impl< ::experiencia, id_mysql >::table_name[] =
  "`experiencia`";

  void access::object_traits_impl< ::experiencia, id_mysql >::
  persist (database& db, const object_type& obj, bool top, bool dyn)
  {
    ODB_POTENTIALLY_UNUSED (top);

    using namespace mysql;

    if (dyn)
    {
      const std::type_info& t (typeid (obj));

      if (t != info.type)
      {
        const info_type& pi (root_traits::map->find (t));
        pi.dispatch (info_type::call_persist, db, &obj, 0);
        return;
      }
    }

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    id_image_type& i (sts.id_image ());
    init (i, id (obj));

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }
  }

  void access::object_traits_impl< ::experiencia, id_mysql >::
  update (database& db, const object_type& obj, bool top, bool dyn)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (top);

    using namespace mysql;
    using mysql::update_statement;

    if (dyn)
    {
      const std::type_info& t (typeid (obj));

      if (t != info.type)
      {
        const info_type& pi (root_traits::map->find (t));
        pi.dispatch (info_type::call_update, db, &obj, 0);
        return;
      }
    }

    mysql::transaction& tr (mysql::transaction::current ());
    mysql::connection& conn (tr.connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& idi (sts.id_image ());
    init (idi, id (obj));

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();
  }

  void access::object_traits_impl< ::experiencia, id_mysql >::
  erase (database& db, const id_type& id, bool top, bool dyn)
  {
    using namespace mysql;

    ODB_POTENTIALLY_UNUSED (top);

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    if (dyn)
    {
      discriminator_type d;
      root_traits::discriminator_ (sts.root_statements (), id, &d);
      const info_type& pi (root_traits::map->find (d));

      if (!pi.derived (info))
        throw object_not_persistent ();

      pi.dispatch (info_type::call_erase, db, 0, &id);
      return;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();
  }

  void access::object_traits_impl< ::experiencia, id_mysql >::
  erase (database& db, const object_type& obj, bool top, bool dyn)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (top);

    if (dyn)
    {
      const std::type_info& t (typeid (obj));

      if (t != info.type)
      {
        const info_type& pi (root_traits::map->find (t));
        pi.dispatch (info_type::call_erase, db, &obj, 0);
        return;
      }
    }

    callback (db, obj, callback_event::pre_erase);
    erase (db, id (obj), true, false);
    callback (db, obj, callback_event::post_erase);
  }

  access::object_traits_impl< ::experiencia, id_mysql >::pointer_type
  access::object_traits_impl< ::experiencia, id_mysql >::
  find (database& db, const id_type& id)
  {
    using namespace mysql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    root_traits::discriminator_type d;

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
      d = root_traits::discriminator (sts.image ());
    }
    else
      root_traits::discriminator_ (sts, id, &d);

    const info_type& pi (root_traits::map->find (d));

    pointer_type p (pi.create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback_event ce (callback_event::pre_load);
      pi.dispatch (info_type::call_callback, db, &obj, &ce);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);

      if (&pi != &info)
      {
        std::size_t d (depth);
        pi.dispatch (info_type::call_load, db, &obj, &d);
      }

      sts.load_delayed (0);
      l.unlock ();
      ce = callback_event::post_load;
      pi.dispatch (info_type::call_callback, db, &obj, &ce);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position (), pi.delayed_loader);

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::experiencia, id_mysql >::
  find (database& db, const id_type& id, object_type& obj, bool dyn)
  {
    ODB_POTENTIALLY_UNUSED (dyn);

    using namespace mysql;

    const std::type_info& t (typeid (obj));
    const info_type& pi (root_traits::map->find (t));
    return pi.dispatch (info_type::call_find, db, &obj, &id);
  }

  bool access::object_traits_impl< ::experiencia, id_mysql >::
  reload (database& db, object_type& obj, bool dyn)
  {
    ODB_POTENTIALLY_UNUSED (dyn);

    using namespace mysql;

    const std::type_info& t (typeid (obj));
    const info_type& pi (root_traits::map->find (t));
    return pi.dispatch (info_type::call_reload, db, &obj, 0);
  }

  bool access::object_traits_impl< ::experiencia, id_mysql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace mysql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  void access::object_traits_impl< ::experiencia, id_mysql >::
  discriminator_ (statements_type& sts,
                  const id_type& id,
                  discriminator_type* pd)
  {
    using namespace mysql;

    id_image_type& idi (sts.discriminator_id_image ());
    init (idi, id);

    binding& idb (sts.discriminator_id_image_binding ());
    if (idi.version != sts.discriminator_id_image_version () ||
        idb.version == 0)
    {
      bind (idb.bind, idi);
      sts.discriminator_id_image_version (idi.version);
      idb.version++;
    }

    discriminator_image_type& i (sts.discriminator_image ());
    binding& imb (sts.discriminator_image_binding ());

    if (i.version != sts.discriminator_image_version () ||
        imb.version == 0)
    {
      MYSQL_BIND* b (imb.bind);
      std::size_t n (0);
      {
        b[n].buffer_type = MYSQL_TYPE_STRING;
        b[n].buffer = i.discriminator_value.data ();
        b[n].buffer_length = static_cast<unsigned long> (
          i.discriminator_value.capacity ());
        b[n].length = &i.discriminator_size;
        b[n].is_null = &i.discriminator_null;
      }

      sts.discriminator_image_version (i.version);
      imb.version++;
    }

    {
      select_statement& st (sts.find_discriminator_statement ());
      st.execute ();
      auto_result ar (st);
      select_statement::result r (st.fetch ());

      if (r == select_statement::no_data)
      {
        throw object_not_persistent ();
      }
      else if (r == select_statement::truncated)
      {
        bool grew (false);
        my_bool* t (sts.discriminator_image_truncated ());

        if (t[0UL])
        {
          i.discriminator_value.capacity (i.discriminator_size);
          grew = true;
        }

        if (grew)
          i.version++;

        if (i.version != sts.discriminator_image_version ())
        {
          MYSQL_BIND* b (imb.bind);
          std::size_t n (0);
          {
            b[n].buffer_type = MYSQL_TYPE_STRING;
            b[n].buffer = i.discriminator_value.data ();
            b[n].buffer_length = static_cast<unsigned long> (
              i.discriminator_value.capacity ());
            b[n].length = &i.discriminator_size;
            b[n].is_null = &i.discriminator_null;
          }

          sts.discriminator_image_version (i.version);
          imb.version++;
          st.refetch ();
        }
      }
    }

    if (pd != 0)
    {
      discriminator_type& d (*pd);
      {
        mysql::value_traits<
            ::std::string,
            mysql::id_string >::set_value (
          d,
          i.discriminator_value,
          i.discriminator_size,
          i.discriminator_null);
      }
    }
  }

  result< access::object_traits_impl< ::experiencia, id_mysql >::object_type >
  access::object_traits_impl< ::experiencia, id_mysql >::
  query (database& db, const query_base_type& q)
  {
    using namespace mysql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::polymorphic_object_result_impl<object_type> > r (
      new (shared) mysql::polymorphic_object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::experiencia, id_mysql >::
  erase_query (database& db, const query_base_type& q)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection (db));

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

#include <odb/post.hxx>
