// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef EXPERIENCIA_ODB_HXX
#define EXPERIENCIA_ODB_HXX

// Begin prologue.
//
#include <odb/boost/version.hxx>
#if ODB_BOOST_VERSION != 2050000 // 2.5.0
#  error ODB and C++ compilers see different libodb-boost interface versions
#endif
#include <odb/boost/date-time/mysql/gregorian-traits.hxx>
#include <odb/boost/date-time/mysql/posix-time-traits.hxx>
//
// End prologue.

#include <odb/version.hxx>

#if ODB_VERSION != 20500UL
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "experiencia.hxx"

#include <memory>
#include <cstddef>
#include <string>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/session.hxx>
#include <odb/cache-traits.hxx>
#include <odb/polymorphic-info.hxx>
#include <odb/result.hxx>
#include <odb/polymorphic-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // experiencia
  //
  template <>
  struct class_traits< ::experiencia >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::experiencia >
  {
    public:
    typedef ::experiencia object_type;
    typedef ::std::shared_ptr< ::experiencia > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = true;

    typedef ::experiencia root_type;
    typedef ::std::string discriminator_type;
    typedef polymorphic_map<object_type> map_type;
    typedef polymorphic_concrete_info<object_type> info_type;
    typedef polymorphic_abstract_info<object_type> abstract_info_type;

    static const std::size_t depth = 1UL;

    typedef ::std::string id_type;

    static const bool auto_id = false;

    static const bool abstract = true;

    static id_type
    id (const object_type&);

    typedef
    odb::pointer_cache_traits<
      pointer_type,
      odb::session >
    pointer_cache_traits;

    typedef
    odb::reference_cache_traits<
      object_type,
      odb::session >
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // experiencia
  //
  template <typename A>
  struct query_columns< ::experiencia, id_mysql, A >
  {
    // nom
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    nom_type_;

    static const nom_type_ nom;

    // typeid_
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    typeid__type_;

    static const typeid__type_ typeid_;

    // descripcio
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    descripcio_type_;

    static const descripcio_type_ descripcio;

    // ciutat
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    ciutat_type_;

    static const ciutat_type_ ciutat;

    // maxim_places
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        int,
        mysql::id_long >::query_type,
      mysql::id_long >
    maxim_places_type_;

    static const maxim_places_type_ maxim_places;

    // preu
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        float,
        mysql::id_float >::query_type,
      mysql::id_float >
    preu_type_;

    static const preu_type_ preu;

    // data_alta
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    data_alta_type_;

    static const data_alta_type_ data_alta;

    // num_reserves
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        int,
        mysql::id_long >::query_type,
      mysql::id_long >
    num_reserves_type_;

    static const num_reserves_type_ num_reserves;
  };

  template <typename A>
  const typename query_columns< ::experiencia, id_mysql, A >::nom_type_
  query_columns< ::experiencia, id_mysql, A >::
  nom (A::table_name, "`nom`", 0);

  template <typename A>
  const typename query_columns< ::experiencia, id_mysql, A >::typeid__type_
  query_columns< ::experiencia, id_mysql, A >::
  typeid_ (A::table_name, "`typeid`", 0);

  template <typename A>
  const typename query_columns< ::experiencia, id_mysql, A >::descripcio_type_
  query_columns< ::experiencia, id_mysql, A >::
  descripcio (A::table_name, "`descripcio`", 0);

  template <typename A>
  const typename query_columns< ::experiencia, id_mysql, A >::ciutat_type_
  query_columns< ::experiencia, id_mysql, A >::
  ciutat (A::table_name, "`ciutat`", 0);

  template <typename A>
  const typename query_columns< ::experiencia, id_mysql, A >::maxim_places_type_
  query_columns< ::experiencia, id_mysql, A >::
  maxim_places (A::table_name, "`maxim_places`", 0);

  template <typename A>
  const typename query_columns< ::experiencia, id_mysql, A >::preu_type_
  query_columns< ::experiencia, id_mysql, A >::
  preu (A::table_name, "`preu`", 0);

  template <typename A>
  const typename query_columns< ::experiencia, id_mysql, A >::data_alta_type_
  query_columns< ::experiencia, id_mysql, A >::
  data_alta (A::table_name, "`data_alta`", 0);

  template <typename A>
  const typename query_columns< ::experiencia, id_mysql, A >::num_reserves_type_
  query_columns< ::experiencia, id_mysql, A >::
  num_reserves (A::table_name, "`num_reserves`", 0);

  template <typename A>
  struct pointer_query_columns< ::experiencia, id_mysql, A >:
    query_columns< ::experiencia, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::experiencia, id_mysql >:
    public access::object_traits< ::experiencia >
  {
    public:
    typedef object_traits_impl<root_type, id_mysql> root_traits;

    struct discriminator_image_type
    {
      details::buffer discriminator_value;
      unsigned long discriminator_size;
      my_bool discriminator_null;

      std::size_t version;
    };

    struct id_image_type
    {
      details::buffer id_value;
      unsigned long id_size;
      my_bool id_null;

      std::size_t version;
    };

    static map_type* map;
    static const abstract_info_type info;

    struct image_type
    {
      // _nom
      //
      details::buffer _nom_value;
      unsigned long _nom_size;
      my_bool _nom_null;

      // typeid_
      //
      details::buffer typeid_value;
      unsigned long typeid_size;
      my_bool typeid_null;

      // _descripcio
      //
      details::buffer _descripcio_value;
      unsigned long _descripcio_size;
      my_bool _descripcio_null;

      // _ciutat
      //
      details::buffer _ciutat_value;
      unsigned long _ciutat_size;
      my_bool _ciutat_null;

      // _maxim_places
      //
      int _maxim_places_value;
      my_bool _maxim_places_null;

      // _preu
      //
      float _preu_value;
      my_bool _preu_null;

      // _data_alta
      //
      details::buffer _data_alta_value;
      unsigned long _data_alta_size;
      my_bool _data_alta_null;

      // _num_reserves
      //
      int _num_reserves_value;
      my_bool _num_reserves_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static discriminator_type
    discriminator (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef
    mysql::polymorphic_root_object_statements<object_type>
    statements_type;

    typedef statements_type root_statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 8UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 1UL;
    static const std::size_t managed_optimistic_column_count = 0UL;
    static const std::size_t discriminator_column_count = 1UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char find_discriminator_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&, bool top = true, bool dyn = true);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&, bool dyn = true);

    static bool
    reload (database&, object_type&, bool dyn = true);

    static void
    update (database&, const object_type&, bool top = true, bool dyn = true);

    static void
    erase (database&, const id_type&, bool top = true, bool dyn = true);

    static void
    erase (database&, const object_type&, bool top = true, bool dyn = true);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);

    static void
    discriminator_ (statements_type&,
                    const id_type&,
                    discriminator_type*);
  };

  template <>
  class access::object_traits_impl< ::experiencia, id_common >:
    public access::object_traits_impl< ::experiencia, id_mysql >
  {
  };

  // experiencia
  //
}

#include "experiencia-odb.ixx"

#include <odb/post.hxx>

#endif // EXPERIENCIA_ODB_HXX
