/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `experiencia`;

CREATE TABLE `experiencia` (
  `nom` VARCHAR(128) NOT NULL PRIMARY KEY,
  `typeid` VARCHAR(128) NOT NULL,
  `descripcio` TEXT NOT NULL,
  `ciutat` TEXT NOT NULL,
  `maxim_places` INT NOT NULL,
  `preu` FLOAT NOT NULL,
  `data_alta` TEXT NOT NULL,
  `num_reserves` INT NOT NULL)
 ENGINE=InnoDB;

