/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `reserva`;

CREATE TABLE IF NOT EXISTS `schema_version` (
  `name` VARCHAR(128) NOT NULL PRIMARY KEY,
  `version` BIGINT UNSIGNED NOT NULL,
  `migration` TINYINT(1) NOT NULL)
 ENGINE=InnoDB;

DELETE FROM `schema_version`
  WHERE `name` = '';

CREATE TABLE `reserva` (
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `data` TEXT NOT NULL,
  `num_places` INT NOT NULL,
  `preu_pagat` FLOAT NOT NULL,
  `usuari` VARCHAR(128) NOT NULL,
  `experiencia` VARCHAR(128) NOT NULL)
 ENGINE=InnoDB;

ALTER TABLE `reserva`
  ADD CONSTRAINT `reserva_usuari_fk`
    FOREIGN KEY (`usuari`)
    REFERENCES `usuari` (`sobrenom`),
  ADD CONSTRAINT `reserva_experiencia_fk`
    FOREIGN KEY (`experiencia`)
    REFERENCES `experiencia` (`nom`);

INSERT IGNORE INTO `schema_version` (
  `name`, `version`, `migration`)
  VALUES ('', 1, 0);

