/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `usuari`;

CREATE TABLE `usuari` (
  `username` VARCHAR(128) NOT NULL PRIMARY KEY,
  `nomcomplet` TEXT NOT NULL,
  `edat` INT NOT NULL)
 ENGINE=InnoDB;

