// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef USUARI_ODB_HXX
#define USUARI_ODB_HXX

#include <odb/version.hxx>

#if ODB_VERSION != 20500UL
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "usuari.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/session.hxx>
#include <odb/cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // usuari
  //
  template <>
  struct class_traits< ::usuari >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::usuari >
  {
    public:
    typedef ::usuari object_type;
    typedef ::std::shared_ptr< ::usuari > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::std::string id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    odb::pointer_cache_traits<
      pointer_type,
      odb::session >
    pointer_cache_traits;

    typedef
    odb::reference_cache_traits<
      object_type,
      odb::session >
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // usuari
  //
  template <typename A>
  struct query_columns< ::usuari, id_mysql, A >
  {
    // username
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    username_type_;

    static const username_type_ username;

    // nomcomplet
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    nomcomplet_type_;

    static const nomcomplet_type_ nomcomplet;

    // edat
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        int,
        mysql::id_long >::query_type,
      mysql::id_long >
    edat_type_;

    static const edat_type_ edat;
  };

  template <typename A>
  const typename query_columns< ::usuari, id_mysql, A >::username_type_
  query_columns< ::usuari, id_mysql, A >::
  username (A::table_name, "`username`", 0);

  template <typename A>
  const typename query_columns< ::usuari, id_mysql, A >::nomcomplet_type_
  query_columns< ::usuari, id_mysql, A >::
  nomcomplet (A::table_name, "`nomcomplet`", 0);

  template <typename A>
  const typename query_columns< ::usuari, id_mysql, A >::edat_type_
  query_columns< ::usuari, id_mysql, A >::
  edat (A::table_name, "`edat`", 0);

  template <typename A>
  struct pointer_query_columns< ::usuari, id_mysql, A >:
    query_columns< ::usuari, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::usuari, id_mysql >:
    public access::object_traits< ::usuari >
  {
    public:
    struct id_image_type
    {
      details::buffer id_value;
      unsigned long id_size;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // _username
      //
      details::buffer _username_value;
      unsigned long _username_size;
      my_bool _username_null;

      // _nomcomplet
      //
      details::buffer _nomcomplet_value;
      unsigned long _nomcomplet_size;
      my_bool _nomcomplet_null;

      // _edat
      //
      int _edat_value;
      my_bool _edat_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 3UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::usuari, id_common >:
    public access::object_traits_impl< ::usuari, id_mysql >
  {
  };

  // usuari
  //
}

#include "usuari-odb.ixx"

#include <odb/post.hxx>

#endif // USUARI_ODB_HXX
